# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: earth
  theme_night: earth
  font: minimal
  font_size: S

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Mapper'
    description: 'Site personnel de Jérémy Garniaux, cartographe et développeur.'
    twitter: 'mapperfr'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Jérémy Garniaux - CC BY SA 2.0.'
    license:
      enable: false
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: fr-fr

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
    enable: true
    extra_languages:
      - r
      - python
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/mapperfr/mapper-web'
    content_dir: content
    branch: master
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
